version: '3.8'

services:
  frontend:
    build: ./client
    container_name: vines
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env

  backend:
    build: ./server
    ports:
      - "3001:3001"
    env_file: .env

  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  db_data:
