name: Docker-Build-Push

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: Quinlan96/vines-frontend
  BACKEND_IMAGE_NAME: Quinlan96/vines-backend
  FRONTEND_WEBHOOK: https://portainer.quinl.in/api/webhooks/638e27d1-7bf4-4432-974d-7f3ddb1afbfb
  BACKEND_WEBHOOK: https://portainer.quinl.in/api/webhooks/df9deb07-74ab-4117-9cba-35fd9ee313fd
  REACT_APP_API_BASE: https://vines.quinl.in/api/v1

  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Frontend Docker metadata
        id: frontend-meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./client
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.frontend-meta.outputs.tags }}
          labels: ${{ steps.frontend-meta.outputs.labels }}
          build-args: |
            REACT_APP_API_BASE=${{ env.REACT_APP_API_BASE }}

      - name: Deploy Frontend Docker image
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.FRONTEND_WEBHOOK }}
          method: 'POST'

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Backend Docker metadata
        id: backend-meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./server
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.backend-meta.outputs.tags }}
          labels: ${{ steps.backend-meta.outputs.labels }}

      - name: Deploy Backend Docker image
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.BACKEND_WEBHOOK }}
          method: 'POST'